### ISSUE TITLE
Error occurs when insert {{_inline_}} template with asyncomplete.vim 

### ISSUE THREAD

**Issue by sgur** [mattn/sonictemplate-vim#38]
I found an error when using sonictemplate-vim with asyncomplete.vim.

How to reproduce:

1. Trigger the SonicTemplate with mapping such as `<C-y>t` (`:Template` command works correctly)
2. Select a snippet using the `{{_inline_}}` keyword.

![2020-01-09 09_17_23-Window](https://user-images.githubusercontent.com/255021/72027336-f0e77900-32c1-11ea-8407-7fcdc36d0b85.png)

My template is like below:
```
has('gui_running') {{_inline_}}
```

Postfix completion also occurs same error.

![2020-01-09 09_53_54-Window](https://user-images.githubusercontent.com/255021/72028520-2e4e0580-32c6-11ea-8272-57ba369bd8e1.png)

The error occurred at [autoload/asyncomplete/utils/_on_change/textchangedp.vim](https://github.com/prabirshrestha/asyncomplete.vim/blob/master/autoload/asyncomplete/utils/_on_change/textchangedp.vim#L52) in asyncomplete.vim.

I assume  that  `TextChangedP` or `TextChangedI` event were triggered but `InsertEnter` was not triggered when expanding `{{_inline_}}` templates (at [#L298](https://github.com/mattn/sonictemplate-vim/blob/master/autoload/sonictemplate.vim#L298) [#L376](https://github.com/mattn/sonictemplate-vim/blob/master/autoload/sonictemplate.vim#L376)).

I think this is fixed when adding `noautocmd` to `normal!` command but I have no idea that either this 
change affects to other part of sonictemplate functionalities or not.

```vim
noautocmd silent! exe "normal! a\<c-r>=c\<cr>"
```

**Comment by mattn** [comment]
Yes, your code in suggestion is right. Could you please make PR ?
